include:
  project: TankerHQ/gitlab-ci-files
  file: /common.yml
  ref: 2021-10-13-215

############
# Workflow #
############

workflow:
  rules:
    # web pipelines for releases only
    - if: $CI_PIPELINE_SOURCE == "web" && ($SDK_RUST_RELEASE_VERSION !~ /\A\d+\.\d+\.\d+(-(alpha|beta)\d+)?\z/ || $SDK_RUST_CARGO_REGISTRY !~ /\A(tanker|tanker-dev)\z/)
      when: never
    # forbid stable releases on registry tanker-dev
    - if: $CI_PIPELINE_SOURCE == "web" && ($SDK_RUST_RELEASE_VERSION =~ /\A\d+\.\d+\.\d+\z/ && $SDK_RUST_CARGO_REGISTRY != "tanker")
      when: never
    - if: !reference [.if-invalid-native-conan-reference, if]
      when: never
    # allow everything else
    - when: always

###########
# Default #
###########

default:
  before_script:
    - poetry run python -m pip install --upgrade pip
    - poetry install
  image: registry.gitlab.com/tankerhq/docker/sdk-rust:latest

##########
# Stages #
##########

stages:
  - build-native
  - check
  - deploy

#############################
# Default settings override #
#############################

.before-script/download-artifacts:
  before_script:
    - poetry run python -m pip install --upgrade pip
    - poetry install
    - poetry run python run-ci.py download-artifacts --project-id=$UPSTREAM_PROJECT_ID --pipeline-id=$UPSTREAM_PIPELINE_ID --job-name=$UPSTREAM_JOB_NAME
    - poetry run python run-ci.py reset-branch $(cat branch_name.txt)
    - poetry run python -m pip install --upgrade pip
    - poetry install

#################
# Extend blocks #
#################

.release-artifacts:
  artifacts:
    paths:
      - native/

############
# profiles #
############

.profiles/linux:
  extends:
    - .tags/linux
  variables:
    TANKER_PROFILES: --profile linux-release

.profiles/windows:
  extends:
    - .tags/windows
  before_script:
    # Powershell doesn't split env variable when expanding it.
    # So, we are using the native syntax to create an array, which will be correctly expanded.
    - $TANKER_PROFILES = "--profile", "vs2019-release-shared"

.profiles/android:
  extends:
    - .tags/linux
  variables:
    TANKER_PROFILES: --profile android-armv8-release-static-http_backend --profile android-x86_64-release-static-http_backend --profile android-x86-release-static-http_backend --profile android-armv7-release-static-http_backend

.profiles/macos/x86_64:
  extends:
    - .tags/macos/x86_64
  variables:
    TANKER_PROFILES: --profile macos-x86_64-release

.profiles/macos/arm:
  extends:
    - .tags/macos/arm
  variables:
    TANKER_PROFILES: --profile macos-armv8-release

.profiles/ios/x86_64:
  extends:
    - .tags/macos/x86_64
  variables:
    TANKER_PROFILES: --profile ios-armv8-release-http_backend --profile ios-simulator-x86_64-release-http_backend

.profiles/ios/arm:
  extends:
    - .tags/macos/arm
  variables:
    TANKER_PROFILES: --profile ios-armv8-release-http_backend --profile ios-simulator-armv8-release-http_backend

######################
# build-native stage #
######################

.rules/build-native:
  rules:
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/mr/manual, rules]
    - !reference [.rules/deploy-pipeline, rules]

.build-native:
  stage: build-native
  extends:
    - .rules/build-native
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home prepare --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE $TANKER_PROFILES

build-native/linux:
  extends:
    - .profiles/linux
    - .build-native

build-native/windows:
  extends:
    - .profiles/windows
    - .build-native

build-native/android:
  extends:
    - .profiles/android
    - .build-native

build-native/macos/x86_64:
  extends:
    - .profiles/macos/x86_64
    - .build-native

build-native/macos/arm:
  extends:
    - .profiles/macos/arm
    - .build-native

build-native/ios/x86_64:
  extends:
    - .profiles/ios/x86_64
    - .build-native

build-native/ios/arm:
  extends:
    - .profiles/ios/arm
    - .build-native


###############
# check stage #
###############

.check/native-from-sources:
  stage: check
  extends:
    - .rules/native-from-sources
  dependencies: []
  script:
    - poetry run python run-ci.py --isolate-conan-user-home prepare --use-tanker=same-as-branch $TANKER_PROFILES
    - poetry run python run-ci.py --isolate-conan-user-home build --test $TANKER_PROFILES


check/native-from-sources/linux:
  extends:
    - .profiles/linux
    - .check/native-from-sources

check/native-from-sources/windows:
  extends:
    - .profiles/windows
    - .check/native-from-sources

check/native-from-sources/android:
  extends:
    - .profiles/android
    - .check/native-from-sources
  variables:
    TANKER_PROFILES: --profile android-armv8-release-static-http_backend --profile android-x86_64-release-static-http_backend --profile android-x86-release-static-http_backend --profile android-armv7-release-static-http_backend

check/native-from-sources/macos/x86_64:
  extends:
    - .profiles/macos/x86_64
    - .check/native-from-sources
  variables:
    TANKER_PROFILES: --profile macos-x86_64-release

check/native-from-sources/macos/arm:
  extends:
    - .profiles/macos/arm
    - .check/native-from-sources
  variables:
    TANKER_PROFILES: --profile macos-armv8-release

check/native-from-sources/ios/x86_64:
  extends:
    - .profiles/ios/x86_64
    - .check/native-from-sources
  variables:
    TANKER_PROFILES: --profile ios-armv8-release-http_backend --profile ios-simulator-x86_64-release-http_backend

check/native-from-sources/ios/arm:
  extends:
    - .profiles/ios/arm
    - .check/native-from-sources
  variables:
    TANKER_PROFILES: --profile ios-armv8-release-http_backend --profile ios-simulator-armv8-release-http_backend

.rules/check/deployed-native:
  rules: !reference [.rules/build-native, rules]

.check/deployed-native:
  stage: check
  extends:
    - .rules/check/deployed-native
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --use-tanker=deployed $TANKER_PROFILES

check/deployed-native/linux:
  extends:
    - .profiles/linux
    - .check/deployed-native
  needs:
    - build-native/linux

check/deployed-native/windows:
  extends:
    - .profiles/windows
    - .check/deployed-native
  needs:
    - build-native/windows

check/deployed-native/android:
  extends:
    - .profiles/android
    - .check/deployed-native
  needs:
    - build-native/android

check/deployed-native/macos/x86_64:
  extends:
    - .profiles/macos/x86_64
    - .check/deployed-native
  needs:
    - build-native/macos/x86_64

check/deployed-native/macos/arm:
  extends:
    - .profiles/macos/arm
    - .check/deployed-native
  needs:
    - build-native/macos/arm

check/deployed-native/ios/x86_64:
  extends:
    - .profiles/ios/x86_64
    - .check/deployed-native
  needs:
    - build-native/ios/x86_64

check/deployed-native/ios/arm:
  extends:
    - .profiles/ios/arm
    - .check/deployed-native
  needs:
    - build-native/ios/arm

.check/downstream:
  stage: check
  extends:
    - .before-script/download-artifacts
  dependencies: []
  script:
    - poetry run python run-ci.py --isolate-conan-user-home prepare --use-tanker=upstream $TANKER_PROFILES
    - poetry run python run-ci.py --isolate-conan-user-home build --test --use-tanker=upstream $TANKER_PROFILES

check/downstream/linux:
  extends:
    - .rules/check/downstream/linux
    - .check/downstream
    - .profiles/linux

check/downstream/windows:
  extends:
    - .rules/check/downstream/windows
    - .check/downstream
    - .profiles/windows

check/downstream/android:
  extends:
    - .rules/check/downstream/android
    - .check/downstream
    - .profiles/android

check/downstream/ios/x86_64:
  extends:
    - .rules/check/downstream/ios
    - .check/downstream
    - .profiles/ios/x86_64

check/downstream/ios/arm:
  extends:
    - .rules/check/downstream/ios
    - .check/downstream
    - .profiles/ios/arm

check/downstream/macos/x86_64:
  extends:
    - .rules/check/downstream/macos/x86_64
    - .check/downstream
    - .profiles/macos/x86_64

check/downstream/macos/arm:
  extends:
    - .rules/check/downstream/macos/arm
    - .check/downstream
    - .profiles/macos/arm

################
# deploy stage #
################

deploy:
  stage: deploy
  extends:
    - .tags/linux
    - .rules/deploy/rust
  script:
    - poetry run python run-ci.py reset-branch $UPSTREAM_BRANCH_NAME
    - poetry run python run-ci.py deploy --version $SDK_RUST_RELEASE_VERSION --registry $SDK_RUST_CARGO_REGISTRY
  needs:
    - build-native/linux
    - build-native/windows
    - build-native/android
    - build-native/macos/x86_64
    - build-native/macos/arm
    - build-native/ios/x86_64
    - build-native/ios/arm
  release:
    description: sdk-rust v$SDK_RUST_RELEASE_VERSION
    tag_name: v$SDK_RUST_RELEASE_VERSION
