include:
  project: TankerHQ/gitlab-ci-files
  file: /rust.yml
  ref: theo/m1_support

check/native-from-sources/linux:
  extends:
    - .check
    - .tags/linux
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile linux-release

check/native-from-sources/android:
  extends:
    - .check
    - .tags/linux
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile android-armv8-release-static --profile android-x86_64-release-static --profile android-x86-release-static --profile android-armv7-release-static

check/native-from-sources/macos/x86_64:
  extends:
    - .check
    - .tags/macos/x86_64
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile macos-x86_64-release

check/native-from-sources/macos/arm:
  extends:
    - .check
    - .tags/macos/arm
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile macos-armv8-release

check/native-from-sources/ios/x86_64:
  extends:
    - .check
    - .tags/macos/x86_64
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile ios-armv8-release --profile ios-simulator-x86_64-release

check/native-from-sources/ios/arm:
  extends:
    - .check
    - .tags/macos/arm
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile ios-armv8-release --profile ios-simulator-armv8-release

check/deployed-native/linux:
  extends:
    - .check
    - .tags/linux
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile linux-release

check/deployed-native/android:
  extends:
    - .check
    - .tags/linux
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile android-armv8-release-static --profile android-x86_64-release-static --profile android-x86-release-static --profile android-armv7-release-static

check/deployed-native/macos/x86_64:
  extends:
    - .check
    - .tags/macos/x86_64
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile macos-x86_64-release

check/deployed-native/macos/arm:
  extends:
    - .check
    - .tags/macos/arm
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile macos-armv8-release

check/deployed-native/ios/x86_64:
  extends:
    - .check
    - .tags/macos/x86_64
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile ios-armv8-release --profile ios-simulator-x86_64-release

check/deployed-native/ios/arm:
  extends:
    - .check
    - .tags/macos/arm
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile ios-armv8-release --profile ios-simulator-armv8-release

check/downstream/linux:
  extends:
    - .check
    - .tags/linux
    - .rules/check/downstream/linux
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile linux-release

check/downstream/android:
  extends:
    - .check
    - .tags/linux
    - .rules/check/downstream/android
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile android-armv8-release-static --profile android-x86_64-release-static --profile android-x86-release-static --profile android-armv7-release-static

check/downstream/ios/x86_64:
  extends:
    - .check
    - .tags/macos/x86_64
    - .rules/check/downstream/ios
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile ios-armv8-release --profile ios-simulator-x86_64-release

check/downstream/ios/arm:
  extends:
    - .check
    - .tags/macos/arm
    - .rules/check/downstream/ios
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile ios-armv8-release --profile ios-simulator-armv8-release

check/downstream/macos/x86_64:
  extends:
    - .check
    - .tags/macos/x86_64
    - .rules/check/downstream/macos/x86_64
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile macos-x86_64-release

check/downstream/macos/arm:
  extends:
    - .check
    - .tags/macos/arm
    - .rules/check/downstream/macos/arm
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile macos-armv8-release

deploy:
  extends:
    - .deploy
    - .tags/linux
    - .rules/deploy/rust
  script:
    - poetry run python run-ci.py reset-branch $UPSTREAM_BRANCH_NAME
    - poetry run python run-ci.py deploy --version $SDK_RUST_RELEASE_VERSION --registry $SDK_RUST_CARGO_REGISTRY
  release:
    description: sdk-rust v$SDK_RUST_RELEASE_VERSION
    tag_name: v$SDK_RUST_RELEASE_VERSION
