include:
  project: TankerHQ/gitlab-ci-files
  file: /rust.yml
  ref: theo/rust

check/native-from-sources/linux:
  extends:
    - .check
    - .tags/linux
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile gcc8-release

check/native-from-sources/android:
  extends:
    - .check
    - .tags/linux
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile android-armv8-release-static --profile android-x86_64-release-static --profile android-x86-release-static --profile android-armv7-release-static

check/native-from-sources/macos:
  extends:
    - .check
    - .tags/macos
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile macos-release

check/native-from-sources/ios:
  extends:
    - .check
    - .tags/macos
    - .rules/native-from-sources
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=same-as-branch --profile ios-armv8-release --profile ios-x86_64-release

check/deployed-native/linux:
  extends:
    - .check
    - .tags/linux
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile gcc8-release

check/deployed-native/android:
  extends:
    - .check
    - .tags/linux
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile android-armv8-release-static --profile android-x86_64-release-static --profile android-x86-release-static --profile android-armv7-release-static

check/deployed-native/macos:
  extends:
    - .check
    - .tags/macos
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile macos-release

check/deployed-native/ios:
  extends:
    - .check
    - .tags/macos
    - .rules/deployed-native/release-artifacts
    - .release-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=deployed --tanker-ref=$SDK_NATIVE_LATEST_CONAN_REFERENCE --profile ios-armv8-release --profile ios-x86_64-release

check/downstream/linux:
  extends:
    - .check
    - .tags/linux
    - .rules/check/downstream/linux
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile gcc8-release

check/downstream/android:
  extends:
    - .check
    - .tags/linux
    - .rules/check/downstream/android
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile android-armv8-release-static --profile android-x86_64-release-static --profile android-x86-release-static --profile android-armv7-release-static

check/downstream/ios:
  extends:
    - .check
    - .tags/macos
    - .rules/check/downstream/ios
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile ios-armv8-release --profile ios-x86_64-release

check/downstream/macos:
  extends:
    - .check
    - .tags/macos
    - .rules/check/downstream/macos
    - .before-script/download-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --use-tanker=upstream --profile macos-release

deploy:
  extends:
    - .deploy
    - .tags/linux
    - .rules/deploy/rust
  script:
    - poetry run python run-ci.py deploy --version $SDK_RUST_RELEASE_VERSION
  release:
    description: sdk-python v$SDK_RUST_RELEASE_VERSION
    tag_name: v$SDK_RUST_RELEASE_VERSION

mirror:
  extends:
    - .deploy
    - .tags/linux
    - .rules/mirror
  script:
    - poetry run python run-ci.py mirror
