[package]
name = "tankersdk"
version = "0.1.0"
edition = "2018"
authors = ["Tanker Team <contact@tanker.io>"]
license = "Apache-2.0"
publish = false

[dependencies]
futures = "0.3"
num_enum = "0.5"
lazy_static = "1.4"
tokio = { version = "0.2", features = ["sync"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
reqwest = { version = "0.10.8", features = ["json", "rustls-tls"], default_features = false }
serde_json = "1.0"
once_cell = "1.4"
rand = "0.7.3"
base64 = "0.12"
variant_count = "1.0"
blake2 = "0.9"
ed25519-dalek = "1.0"
x25519-dalek = "1.1"
